# .github/workflows/build-apk.yml
name: Build CookieM3U8Player APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # --- FIX: Set up Java 17 for AGP 8.x ---
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    # ----------------------------------------
      
    - name: Grant Execute Permission to gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CookieM3U8Player-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 5
